### PR TITLE
Fix mentions not show names, adjust README.md

### PR DESCRIPTION
**Pull request by huybt22**
- Fix mentions sometimes don't show user names but long ID, simply add `!` before user ID
- Current functions should work properly but need more testing to see if the issue is actually fixed.
- Minor README.md adjustment.
- References:
https://stackoverflow.com/a/69759913
https://stackoverflow.com/questions/64214155/discord-py-mention-through-id-doesnt-show-name

### CODE REVIEW

**Review by nitro2 — APPROVED** [review]
Nice!

**Review by neihousaigaai — APPROVED** [review]

**Comment by huybt22** [comment]
I 've just found this :)

`* User mentions with an exclamation mark are deprecated and should be handled like any other user mention.`

https://discord.com/developers/docs/reference#message-formatting

**Comment by nitro2** [comment]
So please revert the change `!`  but keep Readme update.

**Comment by huybt22** [comment]
Closed due to deprecated method.

**Pull request closed without merging**
